# Generated by Django 3.1.5 on 2021-03-11 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='dataInicio',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
