# Generated by Django 3.1.5 on 2021-03-11 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professor', '0001_initial'),
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaSemana', models.CharField(choices=[('SG', 'Segunda-Feira'), ('TR', 'Terça-Feira'), ('QA', 'Quarta-Feira'), ('QI', 'Quinta-Feira'), ('SE', 'Sexta-Feira'), ('SA', 'Sábado'), ('DM', 'Domingo')], default='SG', max_length=2)),
                ('horario', models.TimeField()),
                ('mensalidade', models.FloatField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('nome', models.CharField(max_length=50)),
                ('nivel', models.CharField(choices=[('I1', 'Infantil 1'), ('I2', 'Infantil 2'), ('B1', 'Básico 1'), ('B2', 'Básico 2'), ('I1', 'Intermediário 1'), ('I2', 'Intermediário 2'), ('I3', 'Intermediário 3'), ('A1', 'Avançado 1'), ('A2', 'Avançado 2'), ('A3', 'Avançado 3'), ('P', 'Profissional'), ('O', 'Outro')], default='B1', max_length=2)),
                ('descricao', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.aula')),
            ],
        ),
        migrations.AddField(
            model_name='aula',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.curso'),
        ),
        migrations.AddField(
            model_name='aula',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.professor'),
        ),
    ]
